{{- if and (not .Values.harbor.auth.existingSecret) (not .Values.harbor.vault.enabled) -}}
{{- if or .Values.harbor.auth.username .Values.harbor.auth.password -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "harbor-router.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "harbor-router.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.harbor.auth.username | quote }}
  password: {{ .Values.harbor.auth.password | quote }}
{{- end }}
{{- end }}
