apiVersion: v2
name: harbor-router
description: A high-performance Harbor proxy-cache router
type: application
version: 1.2.1
appVersion: "1.2.1"
home: https://github.com/p2p-org/harbor-router
sources:
  - https://github.com/p2p-org/harbor-router
maintainers:
  - name: p2p-org
keywords:
  - harbor
  - registry
  - proxy
  - cache
  - docker
